sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - pip install codecov
script:
  - docker-compose build
  - docker-compose run web nosetests
after_success:
  - codecov
