sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - pip install codecov
  - pip install coverage
script:
  - docker-compose build
  - docker-compose run web nosetests
